spring.config.import: optional:secret.properties
renderer:
  github:
    organization: spring-guides
    # This optional property may be assigned using a "personal access token" created
    # at https://github.com/settings/applications. It is used for accessing GitHub's
    # API, even for operations that do not require authorization (e.g. Getting Started
    # Guide repositories). This is done in order to work against higher rate limits
    # (5000req/hour vs. the default 60req/hour without a token). When running the app
    # locally, this lower default is fine. When running the app in production, the
    # token is a must. See http://developer.github.com/v3/#rate-limiting.
    token: ${renderer-github-token:}
    webhook:
      secret: ${renderer-github-webhook-secret:changeme}
      action-org: ${renderer-github-webhook-action-org:}
      action-repo: ${renderer-github-webhook-action-repo:}
      dispatch-token: ${renderer-github-webhook-dispatch-token:}
  academy:
    gs-accessing-data-jpa: https://spring.academy/guides/accessing-data-jpa
    gs-rest-service: https://spring.academy/guides/rest-service
    gs-spring-boot: https://spring.academy/guides/building-an-application-with-spring-boot
    gs-messaging-rabbitmq: https://spring.academy/guides/messaging-with-rabbitmq
spring:
  security:
    user:
      password: ${renderer-spring-security-user-password:}
